# -*- coding: utf-8 -*-
"""CollabTesting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gCJT7Ov4qgweiBEpgunGY3MunLzAmn1
"""

!git --version
!git config --global user.email "lawrence_mike@icloud.com"


!git config --global user.name "M1keLawrence"

"""Random text wanted for .py conversion testing"""

print("Hello World")